type: phenopowerlaw

references:
  - T Takeuchi,
    Transactions of the Japan Institute of Metals 16(10):629-640, 1975,
    https://doi.org/10.2320/matertrans1960.16.629,
    fitted from Fig. 3b
  - U.F. Kocks,
    Metallurgical and Materials Transactions B 1:1121–1143, 1970,
    https://doi.org/10.1007/BF02900224

output: [xi_sl, gamma_sl]

N_sl: [12]

n_sl: 20
a_sl: 1.0
h_0_sl-sl: 2.4e+8
xi_0_sl: [1.5e+6]
xi_inf_sl: [112.5e+6]
h_sl-sl: [1, 1, 1.4, 1.4, 1.4, 1.4, 1.4]
dot_gamma_0_sl: 3.e-3
