type: phenopowerlaw

references:
  - F. Wang et al.,
    Acta Materialia 80:77-93, 2014,
    https://doi.org/10.1016/j.actamat.2014.07.048

output: [xi_sl, xi_tw]

N_sl: [3, 3, 6, 0, 6]  # basal, prism, 1. pyr<a>, -, 2. pyr<c+a>
N_tw: [6, 0, 6]        # tension, -, compression

xi_0_sl:   [10.e+6,  55.e+6,  60.e+6, 0.,  60.e+6]
xi_inf_sl: [40.e+6, 135.e+6, 150.e+6, 0., 150.e+6]
xi_0_tw:   [40.e+6, 0., 60.e+6]

a_sl: 2.25
dot_gamma_0_sl: 0.001
dot_gamma_0_tw: 0.001
n_sl: 20
n_tw: 20
f_sat_sl-tw: 10.0

h_0_sl-sl: 500.0e+6
h_0_tw-tw:  50.0e+6
h_0_tw-sl: 150.0e+6
h_sl-sl: [+1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,
          +1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0,  1.0, -1.0,
          -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0,
          -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0,
          -1.0, -1.0, -1.0, -1.0, -1.0, -1.0,  1.0,  1.0,  1.0,  1.0,
          +1.0,  1.0, -1.0, -1.0, -1.0, -1.0,  1.0,  1.0,  1.0,  1.0,
          -1.0, -1.0, -1.0, -1.0,  1.0,  1.0,  1.0,  1.0,  1.0]  # unused entries are indicated by -1.0
h_tw-tw: [+1.0,  1.0, -1.0, -1.0, -1.0, -1.0,  1.0, -1.0,  1.0,  1.0,
          -1.0,  1.0]  # unused entries are indicated by -1.0
h_tw-sl:  [1.0, -1.0,  1.0, -1.0,  1.0, -1.0,  1.0, -1.0,  1.0, -1.0,
           1.0, -1.0, -1.0, -1.0, -1.0, -1.0, +1.0, -1.0,  1.0, -1.0]  # unused entries are indicated by -1.0
h_sl-tw:  [1.0, -1.0,  1.0, -1.0,  1.0, -1.0,  1.0, -1.0,  1.0, -1.0,
           1.0, -1.0, -1.0, -1.0, -1.0, -1.0, +1.0, -1.0,  1.0]  # unused entries are indicated by -1.0
