type: phenopowerlaw

references:
  - C.C. Tasan et al.,
    Acta Materialia 81:386-400, 2014,
    https://doi.org/10.1016/j.actamat.2014.07.071
  - U.F. Kocks,
    Metallurgical and Materials Transactions B 1:1121–1143, 1970,
    https://doi.org/10.1007/BF02900224

output: [xi_sl, gamma_sl]

N_sl: [12, 12]

n_sl: 20
a_sl: 2.25
h_0_sl-sl: 1.0e+9
xi_0_sl: [95.e+6, 96.e+6]
xi_inf_sl: [222.e+6, 412.e+6]
h_sl-sl: [1, 1.4, 1, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4]
dot_gamma_0_sl: 0.001
