type: phenopowerlaw

references:
  - D. Ma et al.,
    Acta Materialia 103:796-808, 2016,
    https://doi.org/10.1016/j.actamat.2015.11.016
  - I. Kovács and G.Vörös,
    International Journal of Plasticity 12:35-43, 1996,
    https://doi.org/10.1016/S0749-6419(95)00043-7
  - U.F. Kocks,
    Metallurgical and Materials Transactions B 1:1121–1143, 1970,
    https://doi.org/10.1007/BF02900224

output: [xi_sl, gamma_sl]

N_sl: [12]

n_sl: 83.3
a_sl: 1.0
h_0_sl-sl: 75.0e+6
xi_0_sl: [26.25e+6]
xi_inf_sl: [53.0e+6]
h_sl-sl: [1, 1, 1.4, 1.4, 1.4, 1.4, 1.4]
dot_gamma_0_sl: 0.001
