type: phenopowerlaw

references:
  - W.F. Hosford et al.,
    Acta Metallurgica 8(3):187-199, 1960,
    https://doi.org/10.1016/0001-6160(60)90127-9,
    fitted from Fig. 5
  - U.F. Kocks,
    Metallurgical and Materials Transactions B 1:1121–1143, 1970,
    https://doi.org/10.1007/BF02900224

output: [xi_sl, gamma_sl]

N_sl: [12]

n_sl: 20
a_sl: 3.1
h_0_sl-sl: 1.7e+8
xi_0_sl: [5.0e+6]
xi_inf_sl: [37.5e+6]
h_sl-sl: [1, 1, 1.4, 1.4, 1.4, 1.4, 1.4]
dot_gamma_0_sl: 7.5e-5
