references:
  - D. Tromans,
    International Journal of Recent Research and Applied Studies 6(4):462-483, 2011,
    https://www.arpapress.com/Volumes/Vol6Issue4/IJRRAS_6_4_14.pdf

lattice: hP
c/a: 1.62350
rho: 1740.0
